version: "3.9"
services:
  app:
    build: .
    container_name: express-ts-app
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && node dist/index.js"
