version: '3.8'

services:
  # Service untuk aplikasi Node.js Anda
  app:
    build: . # Build image dari Dockerfile
    ports:
      # PORT dari .env akan digunakan, atau default ke 3000 jika tidak diset
      - "3000:3000"
    
    # Membaca variabel dari file .env Anda
    env_file:
      - .env

    # MENIMPA DATABASE_URL dari .env dengan alamat khusus Docker
    environment:
      - DATABASE_URL=mysql://root:password@host.docker.internal:3306/shopee_app

    # PENTING: Untuk Docker di Linux, tambahkan ini agar host.docker.internal dikenali
    extra_hosts:
      - "host.docker.internal:host-gateway"